const fs = require('fs');
const path = require('path');

const localizationDir = path.join(__dirname, '..', 'src', 'assets', 'localization');

const newTranslations = {
  ru: {
    MenuClashgramFaq: "FAQ Clashgram",
    MenuPrivacyPolicy: "Политика конфиденциальности",
    ClashgramClientTitle: "Клиент Clashgram",
    ClashgramCustomAnimTip: "Доступные типы фона: animated-gradient, radial-gradient, static-gradient, solid",
    ClashgramCustomAnimPlaceholder: "Вставьте конфигурацию частиц JSON здесь...",
    ClashgramApplyCustomTheme: "Применить кастомную тему",
    MenuClashgramReadOnServer: "Прочитать на сервере",
    ClashgramNoUnreadFound: "Непрочитанные сообщения не найдены",
    ClashgramAllReadSuccess: "Все сообщения успешно прочитаны на сервере",
    MenuClashgramFeatures: "Функции Clashgram",
    ClashgramExportTitle: "Экспорт истории чата",
    ClashgramExportDesc: "Экспортируйте сообщения и медиа из этого чата локально. Экспортируемый контент будет упакован в архив ZIP.",
    ClashgramExportErrBothDates: "Пожалуйста, выберите начальную и конечную даты.",
    ClashgramExportErrDateRange: "Начальная дата не может быть позже конечной.",
    ClashgramExportRange: "Диапазон экспорта",
    ClashgramExportRange50: "Последние 50",
    ClashgramExportRange100: "Последние 100",
    ClashgramExportRangeAll: "Все",
    ClashgramExportRangeDate: "По дате",
    ClashgramExportStartDate: "Начальная дата",
    ClashgramExportEndDate: "Конечная дата",
    ClashgramExportFormat: "Формат",
    ClashgramExportFormatHtml: "HTML (Красивый веб-просмотр)",
    ClashgramExportFormatJson: "JSON (Сырые данные)",
    ClashgramExportMedia: "Медиа для включения",
    ClashgramExportMediaPhotos: "Фотографии",
    ClashgramExportMediaVideos: "Видео",
    ClashgramExportMediaAudios: "Аудиофайлы",
    ClashgramExportMediaVoices: "Голосовые сообщения",
    ClashgramExportMediaStickers: "Стикеры",
    ClashgramExportMediaDocs: "Файлы и документы",
    ClashgramExportProgressFetch: "Подготовка к получению сообщений...",
    ClashgramExportProgressHistory: "Получение истории чата...",
    ClashgramExportProgressMedia: "Проверка и загрузка медиа...",
    ClashgramExportProgressMediaProgress: "Загрузка медиа {completed} из {total}...",
    ClashgramExportProgressStructuring: "Структурирование файла экспорта...",
    ClashgramExportProgressCompressing: "Сжатие ZIP-файла...",
    ClashgramExportProgressTriggering: "Запуск загрузки...",
    ClashgramExportProgressSuccess: "Экспорт успешно завершен!",
    ClashgramExportProgressFailed: "Экспорт не удался.",
    ClashgramExportProgressAborted: "Экспорт отменен.",
    ClashgramExportButtonStart: "Начать экспорт",
    ClashgramExportButtonCancel: "Отмена",
    ClashgramExportButtonClose: "Закрыть",
    ClashgramPasscodeResetLogoutTitle: "Сбросить и выйти?",
    ClashgramPasscodeResetLogoutDesc: "Если вы забыли свои пароли, вам необходимо выйти из своей учетной записи, чтобы очистить их. Это удалит все локальные блокировки.",
    ClashgramPasscodeButtonBack: "Назад",
    ClashgramPasscodeButtonLogoutReset: "Выйти и сбросить",
    ClashgramPasscodeResetPrimary: "Сбросить основной код-пароль",
    ClashgramPasscodeBypassLock: "Обход блокировки",
    ClashgramPasscodeUnlockFolder: "Разблокировать папку",
    ClashgramPasscodeUnlockChat: "Разблокировать чат",
    ClashgramPasscodeRecoveryVerifiedSuccess: "Резервный пароль подтвержден! Выберите новый основной код-пароль длиной не менее 4 символов для разблокировки.",
    ClashgramPasscodeRecoveryBypassDesc: "Введите резервный код-пароль для обхода основной блокировки.",
    ClashgramPasscodeFolderProtectedDesc: "Эта папка защищена локальным код-паролем.",
    ClashgramPasscodeChatProtectedDesc: "Этот чат защищен локальным код-паролем.",
    ClashgramPasscodeErrMinLength: "Код-пароль должен быть не менее 4 символов",
    ClashgramPasscodeErrIncorrectRecovery: "Неверный резервный код-пароль",
    ClashgramPasscodeErrIncorrectPrimary: "Неверный код-пароль, попробуйте еще раз",
    ClashgramPasscodeForgotRecovery: "Забыли резервный пароль тоже?",
    ClashgramPasscodeForgot: "Забыли код-пароль?",
    ClashgramPasscodeButtonCancel: "Отмена",
    ClashgramPasscodeButtonSaveUnlock: "Сохранить и разблокировать",
    ClashgramPasscodeButtonUnlock: "Разблокировать"
  },
  es: {
    MenuClashgramFaq: "Preguntas frecuentes de Clashgram",
    MenuPrivacyPolicy: "Política de privacidad",
    ClashgramClientTitle: "Cliente Clashgram",
    ClashgramCustomAnimTip: "Tipos de fondo disponibles: animated-gradient, radial-gradient, static-gradient, solid",
    ClashgramCustomAnimPlaceholder: "Pegue la configuración de partículas JSON aquí...",
    ClashgramApplyCustomTheme: "Aplicar tema personalizado",
    MenuClashgramReadOnServer: "Leer en el servidor",
    ClashgramNoUnreadFound: "No se encontraron mensajes sin leer",
    ClashgramAllReadSuccess: "Todos los mensajes se leyeron con éxito en el servidor",
    MenuClashgramFeatures: "Funciones de Clashgram",
    ClashgramExportTitle: "Exportar historial de chat",
    ClashgramExportDesc: "Exporte mensajes y multimedia de este chat localmente. El contenido exportado se empaquetará en un archivo ZIP.",
    ClashgramExportErrBothDates: "Por favor, seleccione las fechas de inicio y fin.",
    ClashgramExportErrDateRange: "La fecha de inicio no puede ser posterior a la de finalización.",
    ClashgramExportRange: "Rango de exportación",
    ClashgramExportRange50: "Recientes 50",
    ClashgramExportRange100: "Recientes 100",
    ClashgramExportRangeAll: "Todo",
    ClashgramExportRangeDate: "Por fecha",
    ClashgramExportStartDate: "Fecha de inicio",
    ClashgramExportEndDate: "Fecha de finalización",
    ClashgramExportFormat: "Formato",
    ClashgramExportFormatHtml: "HTML (Vista web hermosa)",
    ClashgramExportFormatJson: "JSON (Datos brutos)",
    ClashgramExportMedia: "Multimedia a incluir",
    ClashgramExportMediaPhotos: "Fotos",
    ClashgramExportMediaVideos: "Videos",
    ClashgramExportMediaAudios: "Archivos de audio",
    ClashgramExportMediaVoices: "Mensajes de voz",
    ClashgramExportMediaStickers: "Stickers",
    ClashgramExportMediaDocs: "Archivos y documentos",
    ClashgramExportProgressFetch: "Preparando obtención de mensajes...",
    ClashgramExportProgressHistory: "Obteniendo historial de chat...",
    ClashgramExportProgressMedia: "Verificando y descargando multimedia...",
    ClashgramExportProgressMediaProgress: "Descargando multimedia {completed} de {total}...",
    ClashgramExportProgressStructuring: "Estructurando archivo de exportación...",
    ClashgramExportProgressCompressing: "Comprimiendo archivo ZIP...",
    ClashgramExportProgressTriggering: "Iniciando descarga...",
    ClashgramExportProgressSuccess: "¡Exportación completada con éxito!",
    ClashgramExportProgressFailed: "Exportación fallida.",
    ClashgramExportProgressAborted: "Exportación abortada.",
    ClashgramExportButtonStart: "Iniciar exportación",
    ClashgramExportButtonCancel: "Cancelar",
    ClashgramExportButtonClose: "Cerrar",
    ClashgramPasscodeResetLogoutTitle: "¿Restablecer y cerrar sesión?",
    ClashgramPasscodeResetLogoutDesc: "Si olvidó sus códigos de acceso, debe cerrar sesión en su cuenta para borrarlos. Esto eliminará todos los bloqueos locales.",
    ClashgramPasscodeButtonBack: "Atrás",
    ClashgramPasscodeButtonLogoutReset: "Cerrar sesión y restablecer",
    ClashgramPasscodeResetPrimary: "Restablecer código principal",
    ClashgramPasscodeBypassLock: "Omitir bloqueo",
    ClashgramPasscodeUnlockFolder: "Desbloquear carpeta",
    ClashgramPasscodeUnlockChat: "Desbloquear chat",
    ClashgramPasscodeRecoveryVerifiedSuccess: "¡Recuperación verificada! Elija un nuevo código de acceso principal de al menos 4 caracteres para desbloquear.",
    ClashgramPasscodeRecoveryBypassDesc: "Introduzca el código de recuperación para omitir el bloqueo principal.",
    ClashgramPasscodeFolderProtectedDesc: "Esta carpeta está protegida por un código de acceso local.",
    ClashgramPasscodeChatProtectedDesc: "Este chat está protegido por un código de acceso local.",
    ClashgramPasscodeErrMinLength: "El código debe tener al menos 4 caracteres",
    ClashgramPasscodeErrIncorrectRecovery: "Código de recuperación incorrecto",
    ClashgramPasscodeErrIncorrectPrimary: "Código incorrecto, intente de nuevo",
    ClashgramPasscodeForgotRecovery: "¿Olvidó el código de recuperación también?",
    ClashgramPasscodeForgot: "¿Olvidó el código de acceso?",
    ClashgramPasscodeButtonCancel: "Cancelar",
    ClashgramPasscodeButtonSaveUnlock: "Guardar y desbloquear",
    ClashgramPasscodeButtonUnlock: "Desbloquear"
  },
  uk: {
    MenuClashgramFaq: "Запитання та відповіді Clashgram",
    MenuPrivacyPolicy: "Політика конфіденційності",
    ClashgramClientTitle: "Клієнт Clashgram",
    ClashgramCustomAnimTip: "Доступні типи фону: animated-gradient, radial-gradient, static-gradient, solid",
    ClashgramCustomAnimPlaceholder: "Вставте конфігурацію частинок JSON сюди...",
    ClashgramApplyCustomTheme: "Застосувати власну тему",
    MenuClashgramReadOnServer: "Прочитати на сервері",
    ClashgramNoUnreadFound: "Непрочитаних повідомлень не знайдено",
    ClashgramAllReadSuccess: "Всі повідомлення успішно прочитано на сервері",
    MenuClashgramFeatures: "Функції Clashgram",
    ClashgramExportTitle: "Експорт історії чату",
    ClashgramExportDesc: "Експортуйте повідомлення та медіа з цього чату локально. Експортований вміст буде упакований в архів ZIP.",
    ClashgramExportErrBothDates: "Будь ласка, виберіть початкову та кінцеву дати.",
    ClashgramExportErrDateRange: "Початкова дата не може бути пізнішою за кінцеву.",
    ClashgramExportRange: "Діапазон експорту",
    ClashgramExportRange50: "Останні 50",
    ClashgramExportRange100: "Останні 100",
    ClashgramExportRangeAll: "Все",
    ClashgramExportRangeDate: "За датою",
    ClashgramExportStartDate: "Початкова дата",
    ClashgramExportEndDate: "Кінцева дата",
    ClashgramExportFormat: "Формат",
    ClashgramExportFormatHtml: "HTML (Гарний веб-перегляд)",
    ClashgramExportFormatJson: "JSON (Сирі дані)",
    ClashgramExportMedia: "Медіа для включення",
    ClashgramExportMediaPhotos: "Фотографії",
    ClashgramExportMediaVideos: "Відео",
    ClashgramExportMediaAudios: "Аудіофайли",
    ClashgramExportMediaVoices: "Голосові повідомлення",
    ClashgramExportMediaStickers: "Стікери",
    ClashgramExportMediaDocs: "Файли та документи",
    ClashgramExportProgressFetch: "Підготовка до завантаження повідомлень...",
    ClashgramExportProgressHistory: "Завантаження історії чату...",
    ClashgramExportProgressMedia: "Перевірка та завантаження медіа...",
    ClashgramExportProgressMediaProgress: "Завантаження медіа {completed} з {total}...",
    ClashgramExportProgressStructuring: "Структурування файлу експорту...",
    ClashgramExportProgressCompressing: "Стиснення ZIP-файлу...",
    ClashgramExportProgressTriggering: "Запуск завантаження...",
    ClashgramExportProgressSuccess: "Експорт успішно завершено!",
    ClashgramExportProgressFailed: "Експорт не вдався.",
    ClashgramExportProgressAborted: "Експорт скасовано.",
    ClashgramExportButtonStart: "Почати експорт",
    ClashgramExportButtonCancel: "Скасувати",
    ClashgramExportButtonClose: "Закрити",
    ClashgramPasscodeResetLogoutTitle: "Скинути та вийти?",
    ClashgramPasscodeResetLogoutDesc: "Якщо ви забули свої паролі, вам необхідно вийти зі свого облікового запису, щоб очистити їх. Це видалить усі локальні блокування.",
    ClashgramPasscodeButtonBack: "Назад",
    ClashgramPasscodeButtonLogoutReset: "Вийти та скинути",
    ClashgramPasscodeResetPrimary: "Скинути основний код-пароль",
    ClashgramPasscodeBypassLock: "Обхід блокування",
    ClashgramPasscodeUnlockFolder: "Розблокувати папку",
    ClashgramPasscodeUnlockChat: "Розблокувати чат",
    ClashgramPasscodeRecoveryVerifiedSuccess: "Резервний пароль підтверджено! Виберіть новий основний код-пароль довжиною не менше 4 символів для розблокування.",
    ClashgramPasscodeRecoveryBypassDesc: "Введіть резервний код-пароль для обходу основного блокування.",
    ClashgramPasscodeFolderProtectedDesc: "Ця папка захищена локальним код-паролем.",
    ClashgramPasscodeChatProtectedDesc: "Цей чат захищений локальним код-паролем.",
    ClashgramPasscodeErrMinLength: "Код-пароль має бути не менше 4 символів",
    ClashgramPasscodeErrIncorrectRecovery: "Невірний резервний код-пароль",
    ClashgramPasscodeErrIncorrectPrimary: "Невірний код-пароль, спробуйте ще раз",
    ClashgramPasscodeForgotRecovery: "Забули резервний пароль також?",
    ClashgramPasscodeForgot: "Забули код-пароль?",
    ClashgramPasscodeButtonCancel: "Скасувати",
    ClashgramPasscodeButtonSaveUnlock: "Зберегти та розблокувати",
    ClashgramPasscodeButtonUnlock: "Розблокувати"
  },
  ar: {
    MenuClashgramFaq: "الأسئلة الشائعة حول كلاشغرام",
    MenuPrivacyPolicy: "سياسة الخصوصية",
    ClashgramClientTitle: "عميل كلاشغرام",
    ClashgramCustomAnimTip: "أنواع الخلفية المتاحة: animated-gradient, radial-gradient, static-gradient, solid",
    ClashgramCustomAnimPlaceholder: "ألصق تكوين الجسيمات JSON هنا...",
    ClashgramApplyCustomTheme: "تطبيق السمة المخصصة",
    MenuClashgramReadOnServer: "قراءة على الخادم",
    ClashgramNoUnreadFound: "لم يتم العثور على رسائل غير مقروءة",
    ClashgramAllReadSuccess: "تم قراءة جميع الرسائل بنجاح على الخادم",
    MenuClashgramFeatures: "ميزات كلاشغرام",
    ClashgramExportTitle: "تصدير تاريخ الدردشة",
    ClashgramExportDesc: "تصدير الرسائل والوسائط من هذه الدردشة محليًا. سيتم تغليف المحتوى المصدر في أرشيف ZIP.",
    ClashgramExportErrBothDates: "يرجى تحديد تاريخي البدء والانتهاء.",
    ClashgramExportErrDateRange: "لا يمكن أن يكون تاريخ البدء بعد تاريخ الانتهاء.",
    ClashgramExportRange: "نطاق التصدير",
    ClashgramExportRange50: "أحدث 50",
    ClashgramExportRange100: "أحدث 100",
    ClashgramExportRangeAll: "الكل",
    ClashgramExportRangeDate: "حسب التاريخ",
    ClashgramExportStartDate: "تاريخ البدء",
    ClashgramExportEndDate: "تاريخ الانتهاء",
    ClashgramExportFormat: "التنسيق",
    ClashgramExportFormatHtml: "HTML (عرض ويب جميل)",
    ClashgramExportFormatJson: "JSON (بيانات أولية)",
    ClashgramExportMedia: "الوسائط التي يجب تضمينها",
    ClashgramExportMediaPhotos: "الصور",
    ClashgramExportMediaVideos: "الفيديوهات",
    ClashgramExportMediaAudios: "الملفات الصوتية",
    ClashgramExportMediaVoices: "الرسائل الصوتية",
    ClashgramExportMediaStickers: "الملصقات",
    ClashgramExportMediaDocs: "الملفات والمستندات",
    ClashgramExportProgressFetch: "جاري التحضير لجلب الرسائل...",
    ClashgramExportProgressHistory: "جاري جلب تاريخ الدردشة...",
    ClashgramExportProgressMedia: "جاري التحقق وتنزيل الوسائط...",
    ClashgramExportProgressMediaProgress: "جاري تنزيل الوسائط {completed} من {total}...",
    ClashgramExportProgressStructuring: "جاري هيكلة ملف التصدير...",
    ClashgramExportProgressCompressing: "جاري ضغط ملف ZIP...",
    ClashgramExportProgressTriggering: "جاري تشغيل التنزيل...",
    ClashgramExportProgressSuccess: "تم التصدير بنجاح!",
    ClashgramExportProgressFailed: "فشل التصدير.",
    ClashgramExportProgressAborted: "تم إلغاء التصدير.",
    ClashgramExportButtonStart: "بدء التصدير",
    ClashgramExportButtonCancel: "إلغاء",
    ClashgramExportButtonClose: "إغلاق",
    ClashgramPasscodeResetLogoutTitle: "إعادة تعيين وتسجيل الخروج؟",
    ClashgramPasscodeResetLogoutDesc: "إذا نسيت رموز المرور الخاصة بك، يجب عليك تسجيل الخروج من حسابك لمسحها. سيؤدي هذا إلى حذف جميع الأقفال المحلية.",
    ClashgramPasscodeButtonBack: "رجوع",
    ClashgramPasscodeButtonLogoutReset: "تسجيل الخروج وإعادة التعيين",
    ClashgramPasscodeResetPrimary: "إعادة تعيين رمز المرور الأساسي",
    ClashgramPasscodeBypassLock: "تجاوز القفل",
    ClashgramPasscodeUnlockFolder: "إلغاء قفل المجلد",
    ClashgramPasscodeUnlockChat: "إلغاء قفل الدردشة",
    ClashgramPasscodeRecoveryVerifiedSuccess: "تم التحقق من الاسترداد! اختر رمز مرور أساسي جديد يتكون من 4 خانات على الأقل لإلغاء القفل.",
    ClashgramPasscodeRecoveryBypassDesc: "أدخل رمز الاسترداد لتجاوز القفل الأساسي.",
    ClashgramPasscodeFolderProtectedDesc: "هذا المجلد محمي بواسطة رمز مرور محلي.",
    ClashgramPasscodeChatProtectedDesc: "هذه الدردشة محمية بواسطة رمز مرور محلي.",
    ClashgramPasscodeErrMinLength: "يجب ألا يقل الرمز عن 4 خانات",
    ClashgramPasscodeErrIncorrectRecovery: "رمز الاسترداد غير صحيح",
    ClashgramPasscodeErrIncorrectPrimary: "رمز غير صحيح، حاول مرة أخرى",
    ClashgramPasscodeForgotRecovery: "هل نسيت رمز الاسترداد أيضًا؟",
    ClashgramPasscodeForgot: "هل نسيت رمز المرور؟",
    ClashgramPasscodeButtonCancel: "إلغاء",
    ClashgramPasscodeButtonSaveUnlock: "حفظ وإلغاء القفل",
    ClashgramPasscodeButtonUnlock: "إلغاء القفل"
  },
  fa: {
    MenuClashgramFaq: "سوالات متداول کلش‌گرام",
    MenuPrivacyPolicy: "سیاست حریم خصوصی",
    ClashgramClientTitle: "کلش‌گرام کلاینت",
    ClashgramCustomAnimTip: "انواع پس‌زمینه در دسترس: animated-gradient, radial-gradient, static-gradient, solid",
    ClashgramCustomAnimPlaceholder: "پیکربندی ذرات JSON را در اینجا وارد کنید...",
    ClashgramApplyCustomTheme: "اعمال پوسته سفارشی",
    MenuClashgramReadOnServer: "خواندن در سرور",
    ClashgramNoUnreadFound: "پیام خوانده نشده‌ای یافت نشد",
    ClashgramAllReadSuccess: "همه پیام‌ها با موفقیت در سرور خوانده شدند",
    MenuClashgramFeatures: "ویژگی‌های کلش‌گرام",
    ClashgramExportTitle: "خروجی گرفتن از تاریخچه گفتگو",
    ClashgramExportDesc: "از پیام‌ها و رسانه‌های این گفتگو به صورت محلی خروجی بگیرید. محتوای صادر شده در یک فایل ZIP بسته‌بندی خواهد شد.",
    ClashgramExportErrBothDates: "لطفاً تاریخ شروع و پایان را انتخاب کنید.",
    ClashgramExportErrDateRange: "تاریخ شروع نمی‌تواند پس از تاریخ پایان باشد.",
    ClashgramExportRange: "محدوده خروجی",
    ClashgramExportRange50: "۵۰ مورد اخیر",
    ClashgramExportRange100: "۱۰۰ مورد اخیر",
    ClashgramExportRangeAll: "همه",
    ClashgramExportRangeDate: "بر اساس تاریخ",
    ClashgramExportStartDate: "تاریخ شروع",
    ClashgramExportEndDate: "تاریخ پایان",
    ClashgramExportFormat: "قالب",
    ClashgramExportFormatHtml: "HTML (نمایش وب زیبا)",
    ClashgramExportFormatJson: "JSON (داده خام)",
    ClashgramExportMedia: "رسانه‌ها جهت خروجی",
    ClashgramExportMediaPhotos: "عکس‌ها",
    ClashgramExportMediaVideos: "ویدیوها",
    ClashgramExportMediaAudios: "فایل‌های صوتی",
    ClashgramExportMediaVoices: "پیام‌های صوتی",
    ClashgramExportMediaStickers: "استیکرها",
    ClashgramExportMediaDocs: "فایل‌ها و اسناد",
    ClashgramExportProgressFetch: "آماده‌سازی برای دریافت پیام‌ها...",
    ClashgramExportProgressHistory: "دریافت تاریخچه گفتگو...",
    ClashgramExportProgressMedia: "بررسی و دانلود رسانه‌ها...",
    ClashgramExportProgressMediaProgress: "دانلود رسانه {completed} از {total}...",
    ClashgramExportProgressStructuring: "ساختاردهی به فایل خروجی...",
    ClashgramExportProgressCompressing: "فشرده‌سازی فایل ZIP...",
    ClashgramExportProgressTriggering: "راه‌اندازی دانلود...",
    ClashgramExportProgressSuccess: "خروجی با موفقیت تکمیل شد!",
    ClashgramExportProgressFailed: "خروجی با خطا مواجه شد.",
    ClashgramExportProgressAborted: "خروجی لغو شد.",
    ClashgramExportButtonStart: "شروع خروجی",
    ClashgramExportButtonCancel: "لغو",
    ClashgramExportButtonClose: "بستن",
    ClashgramPasscodeResetLogoutTitle: "بازنشانی و خروج از حساب؟",
    ClashgramPasscodeResetLogoutDesc: "اگر گذرواژه‌های خود را فراموش کرده‌اید، برای پاک کردن آن‌ها باید از حساب خود خارج شوید. این کار تمام قفل‌های محلی را حذف می‌کند.",
    ClashgramPasscodeButtonBack: "بازگشت",
    ClashgramPasscodeButtonLogoutReset: "خروج و بازنشانی",
    ClashgramPasscodeResetPrimary: "بازنشانی گذرواژه اصلی",
    ClashgramPasscodeBypassLock: "دور زدن قفل",
    ClashgramPasscodeUnlockFolder: "قفل‌گشایی پوشه",
    ClashgramPasscodeUnlockChat: "قفل‌گشایی گفتگو",
    ClashgramPasscodeRecoveryVerifiedSuccess: "کد پشتیبان تایید شد! برای قفل‌گشایی، یک گذرواژه اصلی جدید با حداقل ۴ نویسه انتخاب کنید.",
    ClashgramPasscodeRecoveryBypassDesc: "برای دور زدن قفل اصلی، کد پشتیبان را وارد کنید.",
    ClashgramPasscodeFolderProtectedDesc: "این پوشه توسط گذرواژه محلی محافظت می‌شود.",
    ClashgramPasscodeChatProtectedDesc: "این گفتگو توسط گذرواژه محلی محافظت می‌شود.",
    ClashgramPasscodeErrMinLength: "گذرواژه باید حداقل ۴ نویسه باشد",
    ClashgramPasscodeErrIncorrectRecovery: "کد پشتیبان نادرست است",
    ClashgramPasscodeErrIncorrectPrimary: "گذرواژه نادرست است، دوباره تلاش کنید",
    ClashgramPasscodeForgotRecovery: "کد پشتیبان را هم فراموش کرده‌اید؟",
    ClashgramPasscodeForgot: "گذرواژه را فراموش کرده‌اید؟",
    ClashgramPasscodeButtonCancel: "لغو",
    ClashgramPasscodeButtonSaveUnlock: "ذخیره و قفل‌گشایی",
    ClashgramPasscodeButtonUnlock: "قفل‌گشایی"
  },
  pt: {
    MenuClashgramFaq: "Perguntas frequentes do Clashgram",
    MenuPrivacyPolicy: "Política de privacidade",
    ClashgramClientTitle: "Cliente Clashgram",
    ClashgramCustomAnimTip: "Tipos de fundo disponíveis: animated-gradient, radial-gradient, static-gradient, solid",
    ClashgramCustomAnimPlaceholder: "Cole a configuração de partículas JSON aqui...",
    ClashgramApplyCustomTheme: "Aplicar tema personalizado",
    MenuClashgramReadOnServer: "Ler no Servidor",
    ClashgramNoUnreadFound: "Nenhuma mensagem não lida encontrada",
    ClashgramAllReadSuccess: "Todas as mensagens foram lidas no servidor com sucesso",
    MenuClashgramFeatures: "Recursos do Clashgram",
    ClashgramExportTitle: "Exportar histórico de chat",
    ClashgramExportDesc: "Exporte mensagens e mídias deste chat localmente. O conteúdo exportado será compactado em um arquivo ZIP.",
    ClashgramExportErrBothDates: "Selecione as datas de início e término.",
    ClashgramExportErrDateRange: "A data de início não pode ser posterior à data de término.",
    ClashgramExportRange: "Intervalo de exportação",
    ClashgramExportRange50: "Recentes 50",
    ClashgramExportRange100: "Recentes 100",
    ClashgramExportRangeAll: "Tudo",
    ClashgramExportRangeDate: "Por data",
    ClashgramExportStartDate: "Data de início",
    ClashgramExportEndDate: "Data de término",
    ClashgramExportFormat: "Formato",
    ClashgramExportFormatHtml: "HTML (Visualização web bonita)",
    ClashgramExportFormatJson: "JSON (Dados brutos)",
    ClashgramExportMedia: "Mídias para incluir",
    ClashgramExportMediaPhotos: "Fotos",
    ClashgramExportMediaVideos: "Vídeos",
    ClashgramExportMediaAudios: "Arquivos de áudio",
    ClashgramExportMediaVoices: "Mensagens de voz",
    ClashgramExportMediaStickers: "Stickers",
    ClashgramExportMediaDocs: "Arquivos e documentos",
    ClashgramExportProgressFetch: "Preparando busca de mensagens...",
    ClashgramExportProgressHistory: "Buscando histórico de chat...",
    ClashgramExportProgressMedia: "Verificando e baixando mídias...",
    ClashgramExportProgressMediaProgress: "Baixando mídia {completed} de {total}...",
    ClashgramExportProgressStructuring: "Estruturando arquivo de exportação...",
    ClashgramExportProgressCompressing: "Compactando arquivo ZIP...",
    ClashgramExportProgressTriggering: "Iniciando download...",
    ClashgramExportProgressSuccess: "Exportação concluída com sucesso!",
    ClashgramExportProgressFailed: "Falha na exportação.",
    ClashgramExportProgressAborted: "Exportação abortada.",
    ClashgramExportButtonStart: "Iniciar exportação",
    ClashgramExportButtonCancel: "Cancelar",
    ClashgramExportButtonClose: "Fechar",
    ClashgramPasscodeResetLogoutTitle: "Redefinir e sair?",
    ClashgramPasscodeResetLogoutDesc: "Se você esqueceu suas senhas, deve sair da sua conta para limpá-las. Isso excluirá todos os bloqueios locais.",
    ClashgramPasscodeButtonBack: "Voltar",
    ClashgramPasscodeButtonLogoutReset: "Sair e redefinir",
    ClashgramPasscodeResetPrimary: "Redefinir senha principal",
    ClashgramPasscodeBypassLock: "Bypass Lock",
    ClashgramPasscodeUnlockFolder: "Desbloquear pasta",
    ClashgramPasscodeUnlockChat: "Desbloquear chat",
    ClashgramPasscodeRecoveryVerifiedSuccess: "Recuperação verificada! Escolha uma nova senha principal de pelo menos 4 caracteres para desbloquear.",
    ClashgramPasscodeRecoveryBypassDesc: "Digite a senha de recuperação para ignorar o bloqueio principal.",
    ClashgramPasscodeFolderProtectedDesc: "Esta pasta está protegida por uma senha local.",
    ClashgramPasscodeChatProtectedDesc: "Este chat está protegido por uma senha local.",
    ClashgramPasscodeErrMinLength: "A senha deve ter pelo menos 4 caracteres",
    ClashgramPasscodeErrIncorrectRecovery: "Senha de recuperação incorreta",
    ClashgramPasscodeErrIncorrectPrimary: "Senha incorreta, tente novamente",
    ClashgramPasscodeForgotRecovery: "Esqueceu a senha de recuperação também?",
    ClashgramPasscodeForgot: "Esqueceu a senha?",
    ClashgramPasscodeButtonCancel: "Cancelar",
    ClashgramPasscodeButtonSaveUnlock: "Salvar e desbloquear",
    ClashgramPasscodeButtonUnlock: "Desbloquear"
  },
  "pt-br": {
    MenuClashgramFaq: "Perguntas frequentes do Clashgram",
    MenuPrivacyPolicy: "Política de privacidade",
    ClashgramClientTitle: "Cliente Clashgram",
    ClashgramCustomAnimTip: "Tipos de fundo disponíveis: animated-gradient, radial-gradient, static-gradient, solid",
    ClashgramCustomAnimPlaceholder: "Cole a configuração de partículas JSON aqui...",
    ClashgramApplyCustomTheme: "Aplicar tema personalizado",
    MenuClashgramReadOnServer: "Ler no Servidor",
    ClashgramNoUnreadFound: "Nenhuma mensagem não lida encontrada",
    ClashgramAllReadSuccess: "Todas as mensagens foram lidas no servidor com sucesso",
    MenuClashgramFeatures: "Recursos do Clashgram",
    ClashgramExportTitle: "Exportar histórico de chat",
    ClashgramExportDesc: "Exporte mensagens e mídias deste chat localmente. O conteúdo exportado será compactado em um arquivo ZIP.",
    ClashgramExportErrBothDates: "Selecione as datas de início e término.",
    ClashgramExportErrDateRange: "A data de início não pode ser posterior à data de término.",
    ClashgramExportRange: "Intervalo de exportação",
    ClashgramExportRange50: "Recentes 50",
    ClashgramExportRange100: "Recentes 100",
    ClashgramExportRangeAll: "Tudo",
    ClashgramExportRangeDate: "Por data",
    ClashgramExportStartDate: "Data de início",
    ClashgramExportEndDate: "Data de término",
    ClashgramExportFormat: "Formato",
    ClashgramExportFormatHtml: "HTML (Visualização web bonita)",
    ClashgramExportFormatJson: "JSON (Dados brutos)",
    ClashgramExportMedia: "Mídias para incluir",
    ClashgramExportMediaPhotos: "Fotos",
    ClashgramExportMediaVideos: "Vídeos",
    ClashgramExportMediaAudios: "Arquivos de áudio",
    ClashgramExportMediaVoices: "Mensagens de voz",
    ClashgramExportMediaStickers: "Stickers",
    ClashgramExportMediaDocs: "Arquivos e documentos",
    ClashgramExportProgressFetch: "Preparando busca de mensagens...",
    ClashgramExportProgressHistory: "Buscando histórico de chat...",
    ClashgramExportProgressMedia: "Verificando e baixando mídias...",
    ClashgramExportProgressMediaProgress: "Baixando mídia {completed} de {total}...",
    ClashgramExportProgressStructuring: "Estruturando arquivo de exportação...",
    ClashgramExportProgressCompressing: "Compactando arquivo ZIP...",
    ClashgramExportProgressTriggering: "Iniciando download...",
    ClashgramExportProgressSuccess: "Exportação concluída com sucesso!",
    ClashgramExportProgressFailed: "Falha na exportação.",
    ClashgramExportProgressAborted: "Exportação abortada.",
    ClashgramExportButtonStart: "Iniciar exportação",
    ClashgramExportButtonCancel: "Cancelar",
    ClashgramExportButtonClose: "Fechar",
    ClashgramPasscodeResetLogoutTitle: "Redefinir e sair?",
    ClashgramPasscodeResetLogoutDesc: "Se você esqueceu suas senhas, deve sair da sua conta para limpá-las. Isso excluirá todos os bloqueios locais.",
    ClashgramPasscodeButtonBack: "Voltar",
    ClashgramPasscodeButtonLogoutReset: "Sair e redefinir",
    ClashgramPasscodeResetPrimary: "Redefinir senha principal",
    ClashgramPasscodeBypassLock: "Bypass Lock",
    ClashgramPasscodeUnlockFolder: "Desbloquear pasta",
    ClashgramPasscodeUnlockChat: "Desbloquear chat",
    ClashgramPasscodeRecoveryVerifiedSuccess: "Recuperação verificada! Escolha uma nova senha principal de pelo menos 4 caracteres para desbloquear.",
    ClashgramPasscodeRecoveryBypassDesc: "Digite a senha de recuperação para ignorar o bloqueio principal.",
    ClashgramPasscodeFolderProtectedDesc: "Esta pasta está protegida por uma senha local.",
    ClashgramPasscodeChatProtectedDesc: "Este chat está protegido por uma senha local.",
    ClashgramPasscodeErrMinLength: "A senha deve ter pelo menos 4 caracteres",
    ClashgramPasscodeErrIncorrectRecovery: "Senha de recuperação incorreta",
    ClashgramPasscodeErrIncorrectPrimary: "Senha incorreta, tente novamente",
    ClashgramPasscodeForgotRecovery: "Esqueceu a senha de recuperação também?",
    ClashgramPasscodeForgot: "Esqueceu a senha?",
    ClashgramPasscodeButtonCancel: "Cancelar",
    ClashgramPasscodeButtonSaveUnlock: "Salvar e desbloquear",
    ClashgramPasscodeButtonUnlock: "Desbloquear"
  },
  de: {
    MenuClashgramFaq: "Clashgram FAQ",
    MenuPrivacyPolicy: "Datenschutzerklärung",
    ClashgramClientTitle: "Clashgram-Client",
    ClashgramCustomAnimTip: "Verfügbare Hintergrundtypen: animated-gradient, radial-gradient, static-gradient, solid",
    ClashgramCustomAnimPlaceholder: "Fügen Sie die JSON-Partikelkonfiguration hier ein...",
    ClashgramApplyCustomTheme: "Benutzerdefiniertes Thema anwenden",
    MenuClashgramReadOnServer: "Auf Server lesen",
    ClashgramNoUnreadFound: "Keine ungelesenen Nachrichten gefunden",
    ClashgramAllReadSuccess: "Alle Nachrichten erfolgreich auf dem Server gelesen",
    MenuClashgramFeatures: "Clashgram-Funktionen",
    ClashgramExportTitle: "Chat-Verlauf exportieren",
    ClashgramExportDesc: "Exportieren Sie Nachrichten und Medien aus diesem Chat lokal. Der exportierte Inhalt wird in einem ZIP-Archiv verpackt.",
    ClashgramExportErrBothDates: "Bitte wählen Sie sowohl das Start- als auch das Enddatum aus.",
    ClashgramExportErrDateRange: "Das Startdatum darf nicht nach dem Enddatum liegen.",
    ClashgramExportRange: "Exportbereich",
    ClashgramExportRange50: "Letzte 50",
    ClashgramExportRange100: "Letzte 100",
    ClashgramExportRangeAll: "Alle",
    ClashgramExportRangeDate: "Nach Datum",
    ClashgramExportStartDate: "Startdatum",
    ClashgramExportEndDate: "Enddatum",
    ClashgramExportFormat: "Format",
    ClashgramExportFormatHtml: "HTML (Schöne Webansicht)",
    ClashgramExportFormatJson: "JSON (Rohdaten)",
    ClashgramExportMedia: "Einzuschließende Medien",
    ClashgramExportMediaPhotos: "Fotos",
    ClashgramExportMediaVideos: "Videos",
    ClashgramExportMediaAudios: "Audiodateien",
    ClashgramExportMediaVoices: "Sprachnachrichten",
    ClashgramExportMediaStickers: "Sticker",
    ClashgramExportMediaDocs: "Dateien & Dokumente",
    ClashgramExportProgressFetch: "Vorbereitung des Nachrichtenabrufs...",
    ClashgramExportProgressHistory: "Chat-Verlauf wird abgerufen...",
    ClashgramExportProgressMedia: "Medien werden überprüft und heruntergeladen...",
    ClashgramExportProgressMediaProgress: "Medien werden heruntergeladen: {completed} von {total}...",
    ClashgramExportProgressStructuring: "Exportdatei wird strukturiert...",
    ClashgramExportProgressCompressing: "ZIP-Datei wird komprimiert...",
    ClashgramExportProgressTriggering: "Download wird ausgelöst...",
    ClashgramExportProgressSuccess: "Export erfolgreich abgeschlossen!",
    ClashgramExportProgressFailed: "Export fehlgeschlagen.",
    ClashgramExportProgressAborted: "Export abgebrochen.",
    ClashgramExportButtonStart: "Export starten",
    ClashgramExportButtonCancel: "Abbrechen",
    ClashgramExportButtonClose: "Schließen",
    ClashgramPasscodeResetLogoutTitle: "Zurücksetzen & Abmelden?",
    ClashgramPasscodeResetLogoutDesc: "Wenn Sie Ihre Passcodes vergessen haben, müssen Sie sich von Ihrem Konto abmelden, um sie zu löschen. Dadurch werden alle lokalen Sperren gelöscht.",
    ClashgramPasscodeButtonBack: "Zurück",
    ClashgramPasscodeButtonLogoutReset: "Abmelden & Zurücksetzen",
    ClashgramPasscodeResetPrimary: "Primären Passcode zurücksetzen",
    ClashgramPasscodeBypassLock: "Sperre umgehen",
    ClashgramPasscodeUnlockFolder: "Ordner entsperren",
    ClashgramPasscodeUnlockChat: "Chat entsperren",
    ClashgramPasscodeRecoveryVerifiedSuccess: "Wiederherstellung verifiziert! Wählen Sie einen neuen primären Passcode von mindestens 4 Zeichen aus, um zu entsperren.",
    ClashgramPasscodeRecoveryBypassDesc: "Geben Sie den Wiederherstellungs-Passcode ein, um die primäre Sperre zu umgehen.",
    ClashgramPasscodeFolderProtectedDesc: "Dieser Ordner ist durch einen lokalen Passcode geschützt.",
    ClashgramPasscodeChatProtectedDesc: "Dieser Chat ist durch einen lokalen Passcode geschützt.",
    ClashgramPasscodeErrMinLength: "Der Passcode muss mindestens 4 Zeichen lang sein",
    ClashgramPasscodeErrIncorrectRecovery: "Ungültiger Wiederherstellungs-Passcode",
    ClashgramPasscodeErrIncorrectPrimary: "Falscher Passcode, versuchen Sie es erneut",
    ClashgramPasscodeForgotRecovery: "Wiederherstellungs-Passcode auch vergessen?",
    ClashgramPasscodeForgot: "Passcode vergessen?",
    ClashgramPasscodeButtonCancel: "Abbrechen",
    ClashgramPasscodeButtonSaveUnlock: "Speichern & Entsperren",
    ClashgramPasscodeButtonUnlock: "Entsperren"
  },
  fr: {
    MenuClashgramFaq: "FAQ de Clashgram",
    MenuPrivacyPolicy: "Politique de confidentialité",
    ClashgramClientTitle: "Client Clashgram",
    ClashgramCustomAnimTip: "Types d'arrière-plan disponibles : animated-gradient, radial-gradient, static-gradient, solid",
    ClashgramCustomAnimPlaceholder: "Collez la configuration JSON des particules ici...",
    ClashgramApplyCustomTheme: "Appliquer le thème personnalisé",
    MenuClashgramReadOnServer: "Lire sur le serveur",
    ClashgramNoUnreadFound: "Aucun message non lu trouvé",
    ClashgramAllReadSuccess: "Tous les messages ont été lus avec succès sur le serveur",
    MenuClashgramFeatures: "Fonctionnalités de Clashgram",
    ClashgramExportTitle: "Exporter l'historique du chat",
    ClashgramExportDesc: "Exportez les messages et les médias de ce chat localement. Le contenu exporté sera empaqueté dans une archive ZIP.",
    ClashgramExportErrBothDates: "Veuillez sélectionner les dates de début et de fin.",
    ClashgramExportErrDateRange: "La date de début ne peut pas être postérieure à la date de fin.",
    ClashgramExportRange: "Plage d'exportation",
    ClashgramExportRange50: "50 derniers",
    ClashgramExportRange100: "100 derniers",
    ClashgramExportRangeAll: "Tout",
    ClashgramExportRangeDate: "Par date",
    ClashgramExportStartDate: "Date de début",
    ClashgramExportEndDate: "Date de fin",
    ClashgramExportFormat: "Format",
    ClashgramExportFormatHtml: "HTML (Superbe vue web)",
    ClashgramExportFormatJson: "JSON (Données brutes)",
    ClashgramExportMedia: "Médias à inclure",
    ClashgramExportMediaPhotos: "Photos",
    ClashgramExportMediaVideos: "Vidéos",
    ClashgramExportMediaAudios: "Fichiers audio",
    ClashgramExportMediaVoices: "Messages vocaux",
    ClashgramExportMediaStickers: "Stickers",
    ClashgramExportMediaDocs: "Fichiers & documents",
    ClashgramExportProgressFetch: "Préparation de la récupération des messages...",
    ClashgramExportProgressHistory: "Récupération de l'historique du chat...",
    ClashgramExportProgressMedia: "Vérification et téléchargement des médias...",
    ClashgramExportProgressMediaProgress: "Téléchargement des médias : {completed} sur {total}...",
    ClashgramExportProgressStructuring: "Structuration du fichier d'exportation...",
    ClashgramExportProgressCompressing: "Compression du fichier ZIP...",
    ClashgramExportProgressTriggering: "Déclenchement du téléchargement...",
    ClashgramExportProgressSuccess: "Exportation réussie !",
    ClashgramExportProgressFailed: "Échec de l'exportation.",
    ClashgramExportProgressAborted: "Exportation annulée.",
    ClashgramExportButtonStart: "Démarrer l'exportation",
    ClashgramExportButtonCancel: "Annuler",
    ClashgramExportButtonClose: "Fermer",
    ClashgramPasscodeResetLogoutTitle: "Réinitialiser et se déconnecter ?",
    ClashgramPasscodeResetLogoutDesc: "Si vous avez oublié vos codes, vous devez vous déconnecter de votre compte pour les effacer. Cela supprimera tous les verrous locaux.",
    ClashgramPasscodeButtonBack: "Retour",
    ClashgramPasscodeButtonLogoutReset: "Déconnexion & Réinitialisation",
    ClashgramPasscodeResetPrimary: "Réinitialiser le code principal",
    ClashgramPasscodeBypassLock: "Contourner le verrou",
    ClashgramPasscodeUnlockFolder: "Déverrouiller le dossier",
    ClashgramPasscodeUnlockChat: "Déverrouiller le chat",
    ClashgramPasscodeRecoveryVerifiedSuccess: "Récupération vérifiée ! Choisissez un nouveau code principal d'au moins 4 caractères pour déverrouiller.",
    ClashgramPasscodeRecoveryBypassDesc: "Saisissez le code de récupération pour contourner le verrou principal.",
    ClashgramPasscodeFolderProtectedDesc: "Ce dossier est protégé par un code local.",
    ClashgramPasscodeChatProtectedDesc: "Ce chat est protégé par un code local.",
    ClashgramPasscodeErrMinLength: "Le code doit comporter au moins 4 caractères",
    ClashgramPasscodeErrIncorrectRecovery: "Code de récupération incorrect",
    ClashgramPasscodeErrIncorrectPrimary: "Code incorrect, veuillez réessayer",
    ClashgramPasscodeForgotRecovery: "Code de récupération oublié aussi ?",
    ClashgramPasscodeForgot: "Code de verrouillage oublié ?",
    ClashgramPasscodeButtonCancel: "Annuler",
    ClashgramPasscodeButtonSaveUnlock: "Enregistrer & Déverrouiller",
    ClashgramPasscodeButtonUnlock: "Déverrouiller"
  },
  id: {
    MenuClashgramFaq: "FAQ Clashgram",
    MenuPrivacyPolicy: "Kebijakan Privasi",
    ClashgramClientTitle: "Klien Clashgram",
    ClashgramCustomAnimTip: "Tipe latar belakang yang tersedia: animated-gradient, radial-gradient, static-gradient, solid",
    ClashgramCustomAnimPlaceholder: "Tempel konfigurasi JSON partikel di sini...",
    ClashgramApplyCustomTheme: "Terapkan Tema Kustom",
    MenuClashgramReadOnServer: "Baca di Server",
    ClashgramNoUnreadFound: "Tidak ada pesan yang belum dibaca",
    ClashgramAllReadSuccess: "Semua pesan berhasil dibaca di server",
    MenuClashgramFeatures: "Fitur Clashgram",
    ClashgramExportTitle: "Ekspor Riwayat Obrolan",
    ClashgramExportDesc: "Ekspor pesan dan media dari obrolan ini secara lokal. Konten yang diekspor akan dikemas ke dalam arsip ZIP.",
    ClashgramExportErrBothDates: "Pilih tanggal mulai dan selesai.",
    ClashgramExportErrDateRange: "Tanggal mulai tidak boleh setelah tanggal selesai.",
    ClashgramExportRange: "Rentang Ekspor",
    ClashgramExportRange50: "50 Terkini",
    ClashgramExportRange100: "100 Terkini",
    ClashgramExportRangeAll: "Semua",
    ClashgramExportRangeDate: "Berdasarkan Tanggal",
    ClashgramExportStartDate: "Tanggal Mulai",
    ClashgramExportEndDate: "Tanggal Selesai",
    ClashgramExportFormat: "Format",
    ClashgramExportFormatHtml: "HTML (Tampilan web yang indah)",
    ClashgramExportFormatJson: "JSON (Data mentah)",
    ClashgramExportMedia: "Media untuk disertakan",
    ClashgramExportMediaPhotos: "Foto",
    ClashgramExportMediaVideos: "Video",
    ClashgramExportMediaAudios: "Berkas audio",
    ClashgramExportMediaVoices: "Pesan suara",
    ClashgramExportMediaStickers: "Stiker",
    ClashgramExportMediaDocs: "Berkas & Dokumen",
    ClashgramExportProgressFetch: "Menyiapkan pengambilan pesan...",
    ClashgramExportProgressHistory: "Mengambil riwayat obrolan...",
    ClashgramExportProgressMedia: "Memeriksa dan mengunduh media...",
    ClashgramExportProgressMediaProgress: "Mengunduh media {completed} dari {total}...",
    ClashgramExportProgressStructuring: "Menyusun berkas ekspor...",
    ClashgramExportProgressCompressing: "Mengompresi berkas ZIP...",
    ClashgramExportProgressTriggering: "Memicu unduhan...",
    ClashgramExportProgressSuccess: "Ekspor berhasil diselesaikan!",
    ClashgramExportProgressFailed: "Ekspor gagal.",
    ClashgramExportProgressAborted: "Ekspor dibatalkan.",
    ClashgramExportButtonStart: "Mulai Ekspor",
    ClashgramExportButtonCancel: "Batal",
    ClashgramExportButtonClose: "Tutup",
    ClashgramPasscodeResetLogoutTitle: "Reset & Keluar?",
    ClashgramPasscodeResetLogoutDesc: "Jika Anda lupa kode sandi, Anda harus keluar dari akun untuk menghapusnya. Ini akan menghapus semua kunci lokal.",
    ClashgramPasscodeButtonBack: "Kembali",
    ClashgramPasscodeButtonLogoutReset: "Keluar & Reset",
    ClashgramPasscodeResetPrimary: "Reset Sandi Utama",
    ClashgramPasscodeBypassLock: "Lewati Kunci",
    ClashgramPasscodeUnlockFolder: "Buka Kunci Folder",
    ClashgramPasscodeUnlockChat: "Buka Kunci Obrolan",
    ClashgramPasscodeRecoveryVerifiedSuccess: "Pemulihan terverifikasi! Pilih sandi utama baru minimal 4 karakter untuk membuka kunci.",
    ClashgramPasscodeRecoveryBypassDesc: "Masukkan kode pemulihan untuk melewati kunci utama.",
    ClashgramPasscodeFolderProtectedDesc: "Folder ini dilindungi oleh sandi kunci lokal.",
    ClashgramPasscodeChatProtectedDesc: "Obrolan ini dilindungi oleh sandi kunci lokal.",
    ClashgramPasscodeErrMinLength: "Sandi harus minimal 4 karakter",
    ClashgramPasscodeErrIncorrectRecovery: "Sandi pemulihan salah",
    ClashgramPasscodeErrIncorrectPrimary: "Sandi salah, coba lagi",
    ClashgramPasscodeForgotRecovery: "Lupa sandi pemulihan juga?",
    ClashgramPasscodeForgot: "Lupa sandi?",
    ClashgramPasscodeButtonCancel: "Batal",
    ClashgramPasscodeButtonSaveUnlock: "Simpan & Buka Kunci",
    ClashgramPasscodeButtonUnlock: "Buka Kunci"
  },
  tr: {
    MenuClashgramFaq: "Clashgram SSS",
    MenuPrivacyPolicy: "Gizlilik Politikası",
    ClashgramClientTitle: "Clashgram İstemcisi",
    ClashgramCustomAnimTip: "Kullanılabilir arka plan türleri: animated-gradient, radial-gradient, static-gradient, solid",
    ClashgramCustomAnimPlaceholder: "JSON parçacık yapılandırmasını buraya yapıştırın...",
    ClashgramApplyCustomTheme: "Özel Temayı Uygula",
    MenuClashgramReadOnServer: "Sunucuda Oku",
    ClashgramNoUnreadFound: "Okunmamış mesaj bulunamadı",
    ClashgramAllReadSuccess: "Tüm mesajlar sunucuda başarıyla okundu",
    MenuClashgramFeatures: "Clashgram Özellikleri",
    ClashgramExportTitle: "Sohbet Geçmişini Dışa Aktar",
    ClashgramExportDesc: "Bu sohbetten mesajları ve medyaları yerel olarak dışa aktarın. Dışa aktarılan içerik bir ZIP arşivinde paketlenecektir.",
    ClashgramExportErrBothDates: "Lütfen hem başlangıç hem de bitiş tarihlerini seçin.",
    ClashgramExportErrDateRange: "Başlangıç tarihi bitiş tarihinden sonra olamaz.",
    ClashgramExportRange: "Dışa Aktarma Aralığı",
    ClashgramExportRange50: "Son 50",
    ClashgramExportRange100: "Son 100",
    ClashgramExportRangeAll: "Tümü",
    ClashgramExportRangeDate: "Tarihe Göre",
    ClashgramExportStartDate: "Başlangıç Tarihi",
    ClashgramExportEndDate: "Bitiş Tarihi",
    ClashgramExportFormat: "Biçim",
    ClashgramExportFormatHtml: "HTML (Güzel web görünümü)",
    ClashgramExportFormatJson: "JSON (Ham veri)",
    ClashgramExportMedia: "Dahil edilecek medyalar",
    ClashgramExportMediaPhotos: "Fotoğraflar",
    ClashgramExportMediaVideos: "Videolar",
    ClashgramExportMediaAudios: "Ses dosyaları",
    ClashgramExportMediaVoices: "Sesli mesajlar",
    ClashgramExportMediaStickers: "Stickerlar",
    ClashgramExportMediaDocs: "Dosyalar & Belgeler",
    ClashgramExportProgressFetch: "Mesaj alımı hazırlanıyor...",
    ClashgramExportProgressHistory: "Sohbet geçmişi alınıyor...",
    ClashgramExportProgressMedia: "Medyalar kontrol ediliyor ve indiriliyor...",
    ClashgramExportProgressMediaProgress: "Medya indiriliyor: {completed} / {total}...",
    ClashgramExportProgressStructuring: "Dışa aktarma dosyası yapılandırılıyor...",
    ClashgramExportProgressCompressing: "ZIP dosyası sıkıştırılıyor...",
    ClashgramExportProgressTriggering: "İndirme tetikleniyor...",
    ClashgramExportProgressSuccess: "Dışa aktarma başarıyla tamamlandı!",
    ClashgramExportProgressFailed: "Dışa aktarma başarısız oldu.",
    ClashgramExportProgressAborted: "Dışa aktarma iptal edildi.",
    ClashgramExportButtonStart: "Dışa Aktarmayı Başlat",
    ClashgramExportButtonCancel: "İptal",
    ClashgramExportButtonClose: "Kapat",
    ClashgramPasscodeResetLogoutTitle: "Sıfırla & Çıkış Yap?",
    ClashgramPasscodeResetLogoutDesc: "Şifrelerinizi unuttuysanız, bunları temizlemek için hesabınızdan çıkış yapmalısınız. Bu işlem tüm yerel kilitleri silecektir.",
    ClashgramPasscodeButtonBack: "Geri",
    ClashgramPasscodeButtonLogoutReset: "Çıkış Yap & Sıfırla",
    ClashgramPasscodeResetPrimary: "Birincil Şifreyi Sıfırla",
    ClashgramPasscodeBypassLock: "Kilidi Devre Dışı Bırak",
    ClashgramPasscodeUnlockFolder: "Klasörün Kilidini Aç",
    ClashgramPasscodeUnlockChat: "Sohbetin Kilidini Aç",
    ClashgramPasscodeRecoveryVerifiedSuccess: "Kurtarma doğrulandı! Kilidi açmak için en az 4 karakterden oluşan yeni bir birincil şifre belirleyin.",
    ClashgramPasscodeRecoveryBypassDesc: "Birincil kilidi devre dışı bırakmak için kurtarma şifresini girin.",
    ClashgramPasscodeFolderProtectedDesc: "Bu klasör yerel bir şifre ile korunmaktadır.",
    ClashgramPasscodeChatProtectedDesc: "Bu sohbet yerel bir şifre ile korunmaktadır.",
    ClashgramPasscodeErrMinLength: "Şifre en az 4 karakter olmalıdır",
    ClashgramPasscodeErrIncorrectRecovery: "Geçersiz kurtarma şifresi",
    ClashgramPasscodeErrIncorrectPrimary: "Hatalı şifre, tekrar deneyin",
    ClashgramPasscodeForgotRecovery: "Kurtarma şifresini de mi unuttunuz?",
    ClashgramPasscodeForgot: "Şifrenizi mi unuttunuz?",
    ClashgramPasscodeButtonCancel: "İptal",
    ClashgramPasscodeButtonSaveUnlock: "Kaydet & Kilidi Aç",
    ClashgramPasscodeButtonUnlock: "Kilidi Aç"
  },
  it: {
    MenuClashgramFaq: "FAQ di Clashgram",
    MenuPrivacyPolicy: "Informativa sulla privacy",
    ClashgramClientTitle: "Client Clashgram",
    ClashgramCustomAnimTip: "Tipi di sfondo disponibili: animated-gradient, radial-gradient, static-gradient, solid",
    ClashgramCustomAnimPlaceholder: "Incolla qui la configurazione JSON delle particelle...",
    ClashgramApplyCustomTheme: "Applica tema personalizzato",
    MenuClashgramReadOnServer: "Leggi sul server",
    ClashgramNoUnreadFound: "Nessun messaggio non letto trovato",
    ClashgramAllReadSuccess: "Tutti i messaggi sono stati letti con successo sul server",
    MenuClashgramFeatures: "Funzionalità di Clashgram",
    ClashgramExportTitle: "Esporta cronologia chat",
    ClashgramExportDesc: "Esporta localmente i messaggi e i media di questa chat. Il contenuto esportato verrà pacchettizzato in un archivio ZIP.",
    ClashgramExportErrBothDates: "Seleziona sia la data di inizio che quella di fine.",
    ClashgramExportErrDateRange: "La data di inizio non può essere successiva alla data di fine.",
    ClashgramExportRange: "Intervallo di esportazione",
    ClashgramExportRange50: "Recenti 50",
    ClashgramExportRange100: "Recenti 100",
    ClashgramExportRangeAll: "Tutto",
    ClashgramExportRangeDate: "Per data",
    ClashgramExportStartDate: "Data di inizio",
    ClashgramExportEndDate: "Data di fine",
    ClashgramExportFormat: "Formato",
    ClashgramExportFormatHtml: "HTML (Bellissima visualizzazione web)",
    ClashgramExportFormatJson: "JSON (Dati grezzi)",
    ClashgramExportMedia: "Media da includere",
    ClashgramExportMediaPhotos: "Foto",
    ClashgramExportMediaVideos: "Video",
    ClashgramExportMediaAudios: "File audio",
    ClashgramExportMediaVoices: "Messaggi vocali",
    ClashgramExportMediaStickers: "Sticker",
    ClashgramExportMediaDocs: "File & Documenti",
    ClashgramExportProgressFetch: "Preparazione del recupero dei messaggi...",
    ClashgramExportProgressHistory: "Recupero della cronologia chat...",
    ClashgramExportProgressMedia: "Verifica e download dei media...",
    ClashgramExportProgressMediaProgress: "Download dei media: {completed} di {total}...",
    ClashgramExportProgressStructuring: "Strutturazione del file di esportazione...",
    ClashgramExportProgressCompressing: "Compressione del file ZIP...",
    ClashgramExportProgressTriggering: "Avvio del download...",
    ClashgramExportProgressSuccess: "Esportazione completata con successo!",
    ClashgramExportProgressFailed: "Esportazione fallita.",
    ClashgramExportProgressAborted: "Esportazione annullata.",
    ClashgramExportButtonStart: "Avvia esportazione",
    ClashgramExportButtonCancel: "Annulla",
    ClashgramExportButtonClose: "Chiudi",
    ClashgramPasscodeResetLogoutTitle: "Ripristinare e disconnettersi?",
    ClashgramPasscodeResetLogoutDesc: "Se hai dimenticato i tuoi codici di accesso, devi disconnetterti dal tuo account per cancellarli. Questo eliminerà tutti i blocchi locali.",
    ClashgramPasscodeButtonBack: "Indietro",
    ClashgramPasscodeButtonLogoutReset: "Disconnettiti e ripristina",
    ClashgramPasscodeResetPrimary: "Ripristina passcode principale",
    ClashgramPasscodeBypassLock: "Ignora blocco",
    ClashgramPasscodeUnlockFolder: "Sblocca cartella",
    ClashgramPasscodeUnlockChat: "Sblocca chat",
    ClashgramPasscodeRecoveryVerifiedSuccess: "Recupero verificato! Scegli un nuovo passcode principale di almeno 4 caratteri per sbloccare.",
    ClashgramPasscodeRecoveryBypassDesc: "Inserisci il codice di recupero per ignorare il blocco principale.",
    ClashgramPasscodeFolderProtectedDesc: "Questa cartella è protetta da un passcode locale.",
    ClashgramPasscodeChatProtectedDesc: "Questa chat è protetta da un passcode locale.",
    ClashgramPasscodeErrMinLength: "Il passcode deve contenere almeno 4 caratteri",
    ClashgramPasscodeErrIncorrectRecovery: "Codice di recupero errato",
    ClashgramPasscodeErrIncorrectPrimary: "Codice errato, riprova",
    ClashgramPasscodeForgotRecovery: "Hai dimenticato anche il codice di recupero?",
    ClashgramPasscodeForgot: "Hai dimenticato il passcode?",
    ClashgramPasscodeButtonCancel: "Annulla",
    ClashgramPasscodeButtonSaveUnlock: "Salva & Sblocca",
    ClashgramPasscodeButtonUnlock: "Sblocca"
  }
};

const englishFallback = {
  MenuClashgramFaq: "Clashgram FAQ",
  MenuPrivacyPolicy: "Privacy Policy",
  ClashgramClientTitle: "Clashgram Client",
  ClashgramCustomAnimTip: "Background types: animated-gradient, radial-gradient, static-gradient, solid",
  ClashgramCustomAnimPlaceholder: "Paste particle JSON configuration here...",
  ClashgramApplyCustomTheme: "Apply Custom Theme",
  MenuClashgramReadOnServer: "Read on Server",
  ClashgramNoUnreadFound: "No unread messages found",
  ClashgramAllReadSuccess: "All messages successfully read on server",
  MenuClashgramFeatures: "Clashgram Features",
  ClashgramExportTitle: "Export Chat History",
  ClashgramExportDesc: "Export messages and media from this chat locally. The exported content will be packaged into a ZIP archive.",
  ClashgramExportErrBothDates: "Please select both start and end dates.",
  ClashgramExportErrDateRange: "Start date cannot be after end date.",
  ClashgramExportRange: "Export Range",
  ClashgramExportRange50: "Recent 50",
  ClashgramExportRange100: "Recent 100",
  ClashgramExportRangeAll: "All",
  ClashgramExportRangeDate: "By Date",
  ClashgramExportStartDate: "Start Date",
  ClashgramExportEndDate: "End Date",
  ClashgramExportFormat: "Format",
  ClashgramExportFormatHtml: "HTML (Beautiful web view)",
  ClashgramExportFormatJson: "JSON (Raw data)",
  ClashgramExportMedia: "Media to include",
  ClashgramExportMediaPhotos: "Photos",
  ClashgramExportMediaVideos: "Videos",
  ClashgramExportMediaAudios: "Audio files",
  ClashgramExportMediaVoices: "Voice messages",
  ClashgramExportMediaStickers: "Stickers",
  ClashgramExportMediaDocs: "Files & Documents",
  ClashgramExportProgressFetch: "Preparing message fetch...",
  ClashgramExportProgressHistory: "Fetching chat history...",
  ClashgramExportProgressMedia: "Checking and downloading media...",
  ClashgramExportProgressMediaProgress: "Downloading media {completed}/{total}...",
  ClashgramExportProgressStructuring: "Structuring export file...",
  ClashgramExportProgressCompressing: "Compressing ZIP file...",
  ClashgramExportProgressTriggering: "Triggering download...",
  ClashgramExportProgressSuccess: "Export completed successfully!",
  ClashgramExportProgressFailed: "Export failed.",
  ClashgramExportProgressAborted: "Export aborted.",
  ClashgramExportButtonStart: "Start Export",
  ClashgramExportButtonCancel: "Cancel",
  ClashgramExportButtonClose: "Close",
  ClashgramPasscodeResetLogoutTitle: "Reset & Logout?",
  ClashgramPasscodeResetLogoutDesc: "If you forgot your passcodes, you must log out of your account to clear them. This will delete all local locks.",
  ClashgramPasscodeButtonBack: "Back",
  ClashgramPasscodeButtonLogoutReset: "Logout & Reset",
  ClashgramPasscodeResetPrimary: "Reset Primary Passcode",
  ClashgramPasscodeBypassLock: "Bypass Lock",
  ClashgramPasscodeUnlockFolder: "Unlock Folder",
  ClashgramPasscodeUnlockChat: "Unlock Chat",
  ClashgramPasscodeRecoveryVerifiedSuccess: "Recovery verified! Choose a new primary passcode of at least 4 characters to unlock.",
  ClashgramPasscodeRecoveryBypassDesc: "Enter recovery passcode to bypass primary lock.",
  ClashgramPasscodeFolderProtectedDesc: "This folder is protected by local passcode.",
  ClashgramPasscodeChatProtectedDesc: "This chat is protected by local passcode.",
  ClashgramPasscodeErrMinLength: "Passcode must be at least 4 characters",
  ClashgramPasscodeErrIncorrectRecovery: "Incorrect recovery passcode",
  ClashgramPasscodeErrIncorrectPrimary: "Incorrect passcode, try again",
  ClashgramPasscodeForgotRecovery: "Forgot recovery passcode too?",
  ClashgramPasscodeForgot: "Forgot passcode?",
  ClashgramPasscodeButtonCancel: "Cancel",
  ClashgramPasscodeButtonSaveUnlock: "Save & Unlock",
  ClashgramPasscodeButtonUnlock: "Unlock"
};

// Append to localized files
for (const [locale, data] of Object.entries(newTranslations)) {
  const filePath = path.join(localizationDir, `${locale}.strings`);
  if (fs.existsSync(filePath)) {
    let content = '\n';
    for (const [key, value] of Object.entries(data)) {
      const escapedValue = value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
      content += `"${key}" = "${escapedValue}";\n`;
    }
    fs.appendFileSync(filePath, content, 'utf8');
    console.log(`Appended new translations to ${locale}.strings`);
  }
}

// Append to fallback.strings
const fallbackPath = path.join(localizationDir, 'fallback.strings');
if (fs.existsSync(fallbackPath)) {
  let content = '\n';
  for (const [key, value] of Object.entries(englishFallback)) {
    // Check if key already exists, if so skip or let it override. We will append because custom keys won't collide.
    const escapedValue = value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
    content += `"${key}" = "${escapedValue}";\n`;
  }
  fs.appendFileSync(fallbackPath, content, 'utf8');
  console.log(`Appended new translations to fallback.strings`);
}
